%YAML:1.0

#camera calibration
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480

distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 4.59357e+02
   fy: 4.59764e+02
   cx: 3.32695e+02
   cy: 2.58998e+02
